// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbizajbzfnilagvthcim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiaXphamJ6Zm5pbGFndnRoY2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzIxODksImV4cCI6MjA2NDk0ODE4OX0.aZAFT1-wVCg4yWsiQkaD5ZQ24kWZeR-iTH9XXf1XWZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);